name:                files
version:             0.1.0.0
github:              "githubuser/files"
license:             BSD3
author:              "Charlie Hanley"
maintainer:          "CHanley@Mathematica-mpr.com"
copyright:           "2018 Mathematica Policy Research, Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/files#readme>

dependencies:
- base >= 4.7 && < 5
- turtle

library:
  source-dirs: src

executables:
  files-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - files

tests:
  files-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - files
